DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES(
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL,
  POWER TEXT NOT NULL
)

INSERT INTO TB_HEROES(NAME, POWER)
  VALUES
    ('Flash', 'Velocity'),
    ('Aquaman', 'Speak with animals'),
    ('Batman', 'Money')

SELECT * FROM TB_HEROES
SELECT * FROM TB_HEROES WHERE NAME = 'Flash'

UPDATE TB_HEROES 
  SET NAME = 'Goku', POWER = 'Almost god'
  WHERE ID = 1

DELETE FROM TB_HEROES WHERE ID = 2
